version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout # check out the code in the project directory
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./.env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Pylint
          command: make lint
      - run:
          name: Tests
          command: make -B tests
